
spring:
# database
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    username: postgres
    password: test
    url: jdbc:postgresql://localhost:5432/postgres

# email
  mail:
    host: smtp.gmail.com
    port: 587
    username: whdudal1217@gmail.com
    password: 1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

# app
app:
  host: http://localhost:8080

# spring doc
springdoc:
  packages-to-scan: who.is.neighbor
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /swagger-ui
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

java:
  io:
    temp-directory: temp