version: '3'

services:
  postgres-postgis:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - database_volume:/var/lib/postgresql/data

volumes:
  database_volume: